- name: Install Docker and deploy application
  hosts: webservers
  become: yes
  tasks:

    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/debian bookworm stable"
        state: present

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Enable and start Docker service
      service:
        name: docker
        enabled: yes  
        state: started

    - name: Start ssh-agent on localhost and add SSH key
      delegate_to: localhost
      shell: |
        eval $(ssh-agent -s)
        ssh-add ~/.ssh/gito2

    - name: Pull repository on localhost
      delegate_to: localhost
      git:
        repo: 'git@github.com:mohamedwaleed77/example_docker_application.git'
        dest: /tmp/example_docker_application

    - name: Copy repository to target machines
      copy:
        src: /tmp/example_docker_application/
        dest: /opt/example_docker_application/
        owner: root
        group: root
        mode: '0755'

    - name: Run docker_compose_up
      command: docker compose up -d
      args:
        chdir: /opt/example_docker_application
